/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from "react";
import { 
  TrendingUp, 
  ShoppingBag, 
  DollarSign, 
  PlusCircle, 
  Trash2, 
  Edit, 
  Sparkles, 
  CheckCircle, 
  AlertTriangle,
  Store,
  MapPin,
  MessageSquare
} from "lucide-react";
import { Product, Seller, User } from "../types";

interface SellerDashboardProps {
  isSwahili: boolean;
  isDarkMode: boolean;
  currentUser: User | null;
  activeSeller: Seller | null;
  products: Product[];
  onAddProduct: (product: Omit<Product, "id" | "rating" | "reviewsCount">) => void;
  onEditProduct: (productId: string, updated: Partial<Product>) => void;
  onDeleteProduct: (productId: string) => void;
  onOpenAiHub: (agentType?: "shopping" | "seller" | "support" | "fraud" | "marketing") => void;
}

export default function SellerDashboard({
  isSwahili,
  isDarkMode,
  currentUser,
  activeSeller,
  products,
  onAddProduct,
  onEditProduct,
  onDeleteProduct,
  onOpenAiHub
}: SellerDashboardProps) {
  // Local active product form states
  const [title, setTitle] = useState("");
  const [titleSw, setTitleSw] = useState("");
  const [description, setDescription] = useState("");
  const [descriptionSw, setDescriptionSw] = useState("");
  const [price, setPrice] = useState("");
  const [stock, setStock] = useState("");
  const [category, setCategory] = useState("Traditional Vitenge");
  const [tagsInput, setTagsInput] = useState("");
  const [showAddForm, setShowAddForm] = useState(false);

  // AI draft assistant input states
  const [aiPrompt, setAiPrompt] = useState("");
  const [isAiGenerating, setIsAiGenerating] = useState(false);
  const [aiError, setAiError] = useState("");

  const sellerProducts = products.filter(p => p.sellerId === activeSeller?.id);

  const handleAiSuggest = async () => {
    if (!aiPrompt.trim()) return;
    setIsAiGenerating(true);
    setAiError("");

    try {
      const prompt = `Based on these raw fabric specifications: "${aiPrompt}", please generate an optimized marketplace listing for 'SOKO LA VITENGE MTANDAONI'. Return response as a structured JSON with properties: "title" (English title), "titleSw" (Kiswahili translation), "description" (optimized English description), "descriptionSw" (optimized Kiswahili translation), "recommendedPrice" (realistic price in TSh as an integer e.g. 35000), "category" (Must be one of: "Traditional Vitenge", "Fashion Vitenge", "Wedding Vitenge", "Premium Vitenge", "Imported Vitenge", "Local Designs", "Men's Fabrics", "Women's Fabrics", "Children's Fabrics", "Accessories"), and "tags" (an array of 4-5 relevant strings like ["Morogoro", "Batik", "Cotton"]). DO NOT wrap in markdown, just output raw JSON text.`;
      
      const response = await fetch("/api/ai/agent", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          agentType: "seller",
          prompt: prompt
        })
      });
      const data = await response.json();
      
      // Attempt to parse JSON response. We handle standard clean JSON strings
      let cleanText = data.text;
      // Strip markdown block fences if generated by model fallback
      if (cleanText.includes("```json")) {
        cleanText = cleanText.split("```json")[1].split("```")[0];
      } else if (cleanText.includes("```")) {
        cleanText = cleanText.split("```")[1].split("```")[0];
      }
      
      const result = JSON.parse(cleanText);
      
      setTitle(result.title || "");
      setTitleSw(result.titleSw || "");
      setDescription(result.description || "");
      setDescriptionSw(result.descriptionSw || "");
      setPrice(result.recommendedPrice ? String(result.recommendedPrice) : "35000");
      setCategory(result.category || "Traditional Vitenge");
      setTagsInput(Array.isArray(result.tags) ? result.tags.join(", ") : "");
      
      setAiPrompt("");
    } catch (e) {
      console.error(e);
      setAiError(isSwahili 
        ? "Imeshindwa kutafsiri maelezo. Tafadhali jaribu kuandika sifa zenyewe kwanza au upige kura za mikono." 
        : "Failed to parse AI response. Setting fallback details. Try adding simpler specifications.");
      // Set simple fallbacks
      setTitle("Premium Handcrafted Vitenge Designer Block");
      setTitleSw("Kitenge cha Nta Maridadi cha Kusokotwa");
      setDescription("Authentic, custom crafted high grade fabric.");
      setDescriptionSw("Kitenge bora kabisa cha asili kilichoundwa kiasili.");
      setPrice("38000");
    } finally {
      setIsAiGenerating(false);
    }
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title || !price || !stock || !activeSeller) return;

    onAddProduct({
      title,
      titleSw: titleSw || title,
      description: description || "Authentic Vitenge fabric.",
      descriptionSw: descriptionSw || "Kitenge maridadi cha asili.",
      price: Number(price),
      category,
      sellerId: activeSeller.id,
      sellerName: activeSeller.storeName,
      images: ["/src/assets/images/kitenge_yellow_blue_1782736276162.jpg"],
      variations: [{ id: `v_${Date.now()}`, name: "6 Yards Standard", priceModifier: 0, stock: Number(stock) }],
      stock: Number(stock),
      tags: tagsInput.split(",").map(t => t.trim()).filter(Boolean),
      featured: false,
      trending: false,
      newArrival: true,
      bestSeller: false
    });

    // Reset Form
    setTitle("");
    setTitleSw("");
    setDescription("");
    setDescriptionSw("");
    setPrice("");
    setStock("");
    setTagsInput("");
    setShowAddForm(false);
  };

  if (!currentUser) {
    return (
      <div className="max-w-4xl mx-auto my-12 p-8 text-center bg-amber-500/10 rounded-2xl border border-amber-500/20">
        <h3 className="font-bold text-lg mb-2">
          {isSwahili ? "Mwanachama Pekee!" : "Sellers Only!"}
        </h3>
        <p className="text-xs text-slate-400 mb-4">
          {isSwahili 
            ? "Tafadhali tumia kiigaji cha Mtumiaji (Role Selector) kilicho kwenye kona ya juu kulia kuchagua akaunti ya muuzaji kama Kamala au Mangi."
            : "Please use the Role Selector Simulator in the top-right corner of the Navbar and choose a Seller account to view the dashboard."}
        </p>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 sm:px-6 lg:px-8 space-y-8 animate-fade-in">
      
      {/* Seller Header Profile */}
      <div className={`p-6 rounded-2xl border flex flex-col md:flex-row justify-between items-start md:items-center gap-4 transition-colors ${
        isDarkMode ? "bg-slate-800/60 border-slate-700 text-white" : "bg-slate-50 border-slate-100 text-slate-800"
      }`}>
        <div className="flex items-center gap-4">
          <span className="text-4xl bg-amber-500/10 p-3 rounded-2xl border border-amber-500/30">🏬</span>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-xl font-bold font-sans">
                {activeSeller ? activeSeller.storeName : `${currentUser.name}'s Store`}
              </h2>
              {activeSeller?.verified ? (
                <span className="bg-emerald-500/15 text-emerald-500 border border-emerald-500/20 text-[10px] font-bold px-2 py-0.5 rounded-full flex items-center gap-1">
                  <CheckCircle className="w-3 h-3" />
                  {isSwahili ? "Imethibitishwa" : "Verified Seller"}
                </span>
              ) : (
                <span className="bg-amber-500/15 text-amber-500 border border-amber-500/20 text-[10px] font-bold px-2 py-0.5 rounded-full flex items-center gap-1">
                  <AlertTriangle className="w-3 h-3 animate-pulse" />
                  {isSwahili ? "Inasubiri Uhakiki" : "Verification Pending"}
                </span>
              )}
            </div>
            
            <p className="text-xs text-slate-400 mt-1 max-w-xl flex items-center gap-1">
              <MapPin className="w-3.5 h-3.5 text-amber-500" />
              <span>{activeSeller ? activeSeller.location : "Tanzania East Africa"}</span>
              <span className="mx-2">•</span>
              <span>{activeSeller ? activeSeller.description : ""}</span>
            </p>
          </div>
        </div>

        {/* Action Button */}
        <button
          onClick={() => setShowAddForm(!showAddForm)}
          className="bg-amber-500 hover:bg-amber-600 text-white font-semibold text-xs px-4 py-2.5 rounded-xl transition-all shadow-md hover:scale-105 flex items-center gap-1.5 cursor-pointer"
        >
          <PlusCircle className="w-4 h-4" />
          <span>{showAddForm ? (isSwahili ? "Funga Fomu" : "Close Form") : (isSwahili ? "Ongeza Kitenge kipya" : "Add New Kitenge")}</span>
        </button>
      </div>

      {/* Bento Grid Metrics Analytics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        
        {/* Metric Card 1 */}
        <div className={`p-5 rounded-2xl border transition-colors ${
          isDarkMode ? "bg-slate-800/40 border-slate-700 text-white" : "bg-white border-slate-100 text-slate-800"
        }`}>
          <div className="flex justify-between items-center text-slate-400">
            <span className="text-xs font-semibold">{isSwahili ? "Jumla ya Mapato" : "Total Revenue"}</span>
            <DollarSign className="w-4 h-4 text-amber-500" />
          </div>
          <div className="text-xl font-bold font-sans mt-2 text-amber-500">
            {activeSeller ? activeSeller.revenue.toLocaleString() : "0"} TSh
          </div>
          <p className="text-[10px] text-slate-500 mt-1">
            {isSwahili ? "Mauzo yaliyothibitishwa nchini" : "Cleared mobile money payments"}
          </p>
        </div>

        {/* Metric Card 2 */}
        <div className={`p-5 rounded-2xl border transition-colors ${
          isDarkMode ? "bg-slate-800/40 border-slate-700 text-white" : "bg-white border-slate-100 text-slate-800"
        }`}>
          <div className="flex justify-between items-center text-slate-400">
            <span className="text-xs font-semibold">{isSwahili ? "Vitenge Vilivyouzwa" : "Fabrics Sold"}</span>
            <TrendingUp className="w-4 h-4 text-emerald-500" />
          </div>
          <div className="text-xl font-bold font-sans mt-2">
            {activeSeller ? activeSeller.salesCount : "0"} {isSwahili ? "Yadi/Vipande" : "Pcs / Yards"}
          </div>
          <p className="text-[10px] text-emerald-500 mt-1 font-semibold">
            {isSwahili ? "Ukuaji thabiti wa soko" : "Steady organic customer growth"}
          </p>
        </div>

        {/* Metric Card 3 */}
        <div className={`p-5 rounded-2xl border transition-colors ${
          isDarkMode ? "bg-slate-800/40 border-slate-700 text-white" : "bg-white border-slate-100 text-slate-800"
        }`}>
          <div className="flex justify-between items-center text-slate-400">
            <span className="text-xs font-semibold">{isSwahili ? "Bidhaa Sokoni" : "Active Listings"}</span>
            <ShoppingBag className="w-4 h-4 text-purple-500" />
          </div>
          <div className="text-xl font-bold font-sans mt-2">
            {sellerProducts.length} {isSwahili ? "Vitenge" : "Items"}
          </div>
          <p className="text-[10px] text-slate-500 mt-1">
            {isSwahili ? "Zote ziko hai na zinasomeka" : "All online and searchable"}
          </p>
        </div>

        {/* Metric Card 4 - Assistant shortcut */}
        <div 
          onClick={() => onOpenAiHub("seller")}
          className="p-5 rounded-2xl border border-amber-500/20 bg-gradient-to-br from-amber-500/10 to-amber-600/10 hover:from-amber-500/15 hover:to-amber-600/15 transition-all cursor-pointer flex flex-col justify-between"
        >
          <div className="flex justify-between items-center text-amber-500">
            <span className="text-xs font-bold uppercase tracking-wider">{isSwahili ? "Msaidizi wa AI" : "AI Copilot Active"}</span>
            <Sparkles className="w-4 h-4 text-amber-500 animate-spin" />
          </div>
          <div>
            <div className="text-xs font-bold text-slate-300 mt-2">
              {isSwahili ? "Unda Maelezo ya Vitenge na Bei" : "Generate descriptions & recommend prices"}
            </div>
            <p className="text-[9px] text-amber-500/80 mt-1 underline">
              {isSwahili ? "Uliza Msaidizi sasa" : "Click to chat with AI listing agent"}
            </p>
          </div>
        </div>

      </div>

      {/* AI Listing Creator Block */}
      {showAddForm && (
        <div className={`p-6 rounded-2xl border transition-all ${
          isDarkMode ? "bg-slate-800/60 border-amber-500/30" : "bg-amber-500/5 border-amber-500/20"
        }`}>
          
          <div className="flex items-center gap-2 mb-4">
            <Sparkles className="w-5 h-5 text-amber-500 animate-pulse" />
            <h3 className="font-bold text-sm text-amber-500">
              {isSwahili ? "AI MSAIDIZI: Usanifu wa Bidhaa kiotomatiki" : "AI ASSISTANT: Generate listings automatically"}
            </h3>
          </div>

          <div className="space-y-3 mb-6">
            <p className="text-xs text-slate-400">
              {isSwahili 
                ? "Andika kwa ufupi sifa za Kitenge chako (mf. 'Batik yenye rangi ya njano na nyeusi, iliyotengenezwa Morogoro, 6 yards') kisha bofya kitufe cha AI ili kupata jina, bei bora na maelezo mazuri ya kiswahili na kiingereza mara moja!"
                : "Type short fabric details below (e.g. 'Morogoro Batik yellow and black, 6 yards') and let Gemini write highly descriptive copy, translations, pricing, and tag suggestions!"}
            </p>
            
            <div className="flex gap-2">
              <input
                type="text"
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder={isSwahili ? "mf. Wax Print ya pamba ya bluu na dhahabu..." : "e.g. Royal Blue and gold wax cotton print..."}
                className={`flex-1 text-xs px-4 py-3 rounded-xl border focus:outline-hidden ${
                  isDarkMode ? "bg-slate-900 border-slate-700 text-white" : "bg-white border-slate-200 text-slate-800"
                }`}
              />
              <button
                type="button"
                onClick={handleAiSuggest}
                disabled={!aiPrompt.trim() || isAiGenerating}
                className="bg-amber-500 hover:bg-amber-600 disabled:opacity-55 text-white font-bold text-xs px-4 py-3 rounded-xl transition-all flex items-center gap-1 shadow-md cursor-pointer shrink-0"
              >
                <Sparkles className="w-4 h-4" />
                <span>{isAiGenerating ? (isSwahili ? "Inasoma..." : "Generating...") : (isSwahili ? "Tengeneza kwa AI" : "AI Generate")}</span>
              </button>
            </div>
            {aiError && <p className="text-xs text-rose-500 font-semibold">{aiError}</p>}
          </div>

          <hr className="border-slate-700/20 my-6" />

          {/* Form inputs */}
          <form onSubmit={handleFormSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-4">
            
            <div>
              <label className="block text-xs font-bold text-slate-400 mb-1.5">{isSwahili ? "Jina la Kitenge (Kiingereza)" : "Title (English)"}</label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                required
                className={`w-full text-xs px-4 py-2.5 rounded-xl border focus:outline-hidden ${
                  isDarkMode ? "bg-slate-900 border-slate-700 text-white" : "bg-white border-slate-200 text-slate-800"
                }`}
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-400 mb-1.5">{isSwahili ? "Jina la Kitenge (Kiswahili)" : "Title (Swahili)"}</label>
              <input
                type="text"
                value={titleSw}
                onChange={(e) => setTitleSw(e.target.value)}
                className={`w-full text-xs px-4 py-2.5 rounded-xl border focus:outline-hidden ${
                  isDarkMode ? "bg-slate-900 border-slate-700 text-white" : "bg-white border-slate-200 text-slate-800"
                }`}
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-xs font-bold text-slate-400 mb-1.5">{isSwahili ? "Maelezo ya Kitenge (Kiingereza)" : "Description (English)"}</label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={3}
                className={`w-full text-xs p-4 rounded-xl border focus:outline-hidden ${
                  isDarkMode ? "bg-slate-900 border-slate-700 text-white" : "bg-white border-slate-200 text-slate-800"
                }`}
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-xs font-bold text-slate-400 mb-1.5">{isSwahili ? "Maelezo ya Kitenge (Kiswahili)" : "Description (Swahili)"}</label>
              <textarea
                value={descriptionSw}
                onChange={(e) => setDescriptionSw(e.target.value)}
                rows={3}
                className={`w-full text-xs p-4 rounded-xl border focus:outline-hidden ${
                  isDarkMode ? "bg-slate-900 border-slate-700 text-white" : "bg-white border-slate-200 text-slate-800"
                }`}
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-400 mb-1.5">{isSwahili ? "Bei (TSh)" : "Price (TSh)"}</label>
              <input
                type="number"
                value={price}
                onChange={(e) => setPrice(e.target.value)}
                required
                className={`w-full text-xs px-4 py-2.5 rounded-xl border focus:outline-hidden ${
                  isDarkMode ? "bg-slate-900 border-slate-700 text-white" : "bg-white border-slate-200 text-slate-800"
                }`}
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-400 mb-1.5">{isSwahili ? "Kiasi cha Stock (Yadi)" : "Stock Quantity (Yards)"}</label>
              <input
                type="number"
                value={stock}
                onChange={(e) => setStock(e.target.value)}
                required
                className={`w-full text-xs px-4 py-2.5 rounded-xl border focus:outline-hidden ${
                  isDarkMode ? "bg-slate-900 border-slate-700 text-white" : "bg-white border-slate-200 text-slate-800"
                }`}
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-400 mb-1.5">{isSwahili ? "Kundi la Kitenge" : "Fabric Category"}</label>
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className={`w-full text-xs px-4 py-2.5 rounded-xl border focus:outline-hidden ${
                  isDarkMode ? "bg-slate-900 border-slate-700 text-white" : "bg-white border-slate-200 text-slate-800"
                }`}
              >
                <option value="Traditional Vitenge">{isSwahili ? "Traditional Vitenge" : "Traditional Vitenge"}</option>
                <option value="Fashion Vitenge">{isSwahili ? "Fashion Vitenge" : "Fashion Vitenge"}</option>
                <option value="Wedding Vitenge">{isSwahili ? "Wedding Vitenge" : "Wedding Vitenge"}</option>
                <option value="Premium Vitenge">{isSwahili ? "Premium Vitenge" : "Premium Vitenge"}</option>
                <option value="Imported Vitenge">{isSwahili ? "Imported Vitenge" : "Imported Vitenge"}</option>
                <option value="Local Designs">{isSwahili ? "Local Designs" : "Local Designs"}</option>
                <option value="Men's Fabrics">{isSwahili ? "Men's Fabrics" : "Men's Fabrics"}</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-400 mb-1.5">{isSwahili ? "Vitambulisho / Tags (Tenganisha kwa mkato)" : "Tags / Hashtags (Separated by comma)"}</label>
              <input
                type="text"
                value={tagsInput}
                onChange={(e) => setTagsInput(e.target.value)}
                placeholder="mf. Cotton, Wax, Wedding"
                className={`w-full text-xs px-4 py-2.5 rounded-xl border focus:outline-hidden ${
                  isDarkMode ? "bg-slate-900 border-slate-700 text-white" : "bg-white border-slate-200 text-slate-800"
                }`}
              />
            </div>

            <div className="md:col-span-2 pt-2">
              <button
                type="submit"
                className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs py-3 rounded-xl transition-all shadow-md cursor-pointer"
              >
                💾 {isSwahili ? "Hifadhi na Tuma Sokoni" : "Publish & Upload Kitenge Fabric"}
              </button>
            </div>

          </form>

        </div>
      )}

      {/* Seller Active Products list */}
      <div className="space-y-4">
        <h3 className="font-bold text-base font-sans tracking-tight">
          {isSwahili ? "Vitenge vyako vilivyo sokoni" : "Your Active Fabric Catalog"}
        </h3>

        {sellerProducts.length === 0 ? (
          <div className="text-center py-12 border-2 border-dashed border-slate-700/20 rounded-2xl">
            <p className="text-xs text-slate-500">
              {isSwahili ? "Hujachapisha Kitenge chochote bado." : "You have not uploaded any fabric products yet."}
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {sellerProducts.map((p) => (
              <div 
                key={p.id} 
                className={`rounded-2xl border overflow-hidden flex flex-col transition-all hover:shadow-lg ${
                  isDarkMode ? "bg-slate-800/40 border-slate-700 text-white" : "bg-white border-slate-100 text-slate-800"
                }`}
              >
                <div className="h-44 relative bg-slate-100 dark:bg-slate-950 overflow-hidden">
                  <img
                    src={p.images[0]}
                    alt={p.title}
                    referrerPolicy="no-referrer"
                    className="w-full h-full object-cover transition-transform hover:scale-110"
                  />
                  <span className="absolute top-3 left-3 bg-slate-900/80 text-amber-500 text-[10px] font-bold py-1 px-2.5 rounded-full font-mono">
                    {p.category}
                  </span>
                </div>

                <div className="p-4 flex-1 flex flex-col justify-between">
                  <div>
                    <h4 className="font-bold text-sm tracking-tight line-clamp-1">
                      {isSwahili ? p.titleSw : p.title}
                    </h4>
                    <p className="text-[11px] text-slate-400 mt-1 line-clamp-2">
                      {isSwahili ? p.descriptionSw : p.description}
                    </p>
                    <div className="text-amber-500 font-bold font-mono text-sm mt-2">
                      {p.price.toLocaleString()} TSh
                    </div>
                  </div>

                  <div className="mt-4 pt-3 border-t border-slate-700/10 flex justify-between items-center text-xs text-slate-400">
                    <span>{isSwahili ? "Stock" : "Stock"}: <b>{p.stock}</b></span>
                    
                    <div className="flex gap-2">
                      <button
                        onClick={() => {
                          const newPrice = prompt("Enter new price (TSh):", String(p.price));
                          if (newPrice) {
                            onEditProduct(p.id, { price: Number(newPrice) });
                          }
                        }}
                        title="Quick Edit Price"
                        className="p-1.5 rounded-lg bg-amber-500/10 text-amber-500 hover:bg-amber-500/20 cursor-pointer"
                      >
                        <Edit className="w-3.5 h-3.5" />
                      </button>
                      <button
                        onClick={() => {
                          if (confirm(isSwahili ? "Unataka kufuta Kitenge hiki?" : "Delete this Kitenge fabric?")) {
                            onDeleteProduct(p.id);
                          }
                        }}
                        title="Delete Product"
                        className="p-1.5 rounded-lg bg-rose-500/10 text-rose-500 hover:bg-rose-500/20 cursor-pointer"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  );
}
